version: "3.9"

services:
  shoes-market:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: shoes-market
    restart: always
    depends_on:
      create-admin:
        condition: service_completed_successfully
    command: >
      gunicorn shoes_market.main:app
      -k uvicorn.workers.UvicornWorker
      --workers 4
      --bind 0.0.0.0:8000
      --access-logfile -
      --error-logfile -
      --log-level info
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/project
      - /project/bin
    networks:
      main: { }

  migrate:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - shoes-market-db
    env_file:
      - .env
    command: alembic upgrade head
    networks:
      main: { }

  create-admin:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: python -m shoes_market.create_admin
    networks:
      main: { }

  shoes-market-db:
    image: postgres:14.7-alpine
    container_name: shoes-market-db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      main: { }

  shoes-market-redis:
    image: redis:7.0-alpine
    networks:
      main: { }

networks:
  main: {}

volumes:
  postgres_data: