version: "3.9"

services:
  shoes-market:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: shoes-market
    restart: always
    depends_on:
      - shoes-market-db
    command: uvicorn shoes_market.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/project
      - /project/bin
    networks:
      main: { }

  shoes-market-db:
    image: postgres:14.7-alpine
    container_name: shoes-market-db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - ./local_postgres_data:/var/lib/postgresql/data
    networks:
      main: { }

  shoes-market-redis:
    image: redis:7.0-alpine
    networks:
      main: { }

networks:
  main: {}