"""empty message

Revision ID: 307fde8c074d
Revises: 23716aba6847
Create Date: 2026-06-21 04:32:25.013475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307fde8c074d'
down_revision = '23716aba6847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product', sa.Column('article', sa.String(length=255), nullable=False))
    op.add_column('tags_tag', sa.Column('type', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_tags_tag_type'), 'tags_tag', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_tag_type'), table_name='tags_tag')
    op.drop_column('tags_tag', 'type')
    op.drop_column('products_product', 'article')
    # ### end Alembic commands ###
