"""empty message

Revision ID: 8f2edfeea72f
Revises: 
Create Date: 2023-07-21 15:20:05.142236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2edfeea72f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_product',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products_product', ['id'], unique=False)
    op.create_table('tags_tag',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tag_id'), 'tags_tag', ['id'], unique=False)
    op.create_index(op.f('ix_tags_tag_name'), 'tags_tag', ['name'], unique=True)
    op.create_table('users_user',
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users_user', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_nickname'), 'users_user', ['nickname'], unique=False)
    op.create_index(op.f('ix_users_user_phone_number'), 'users_user', ['phone_number'], unique=True)
    op.create_table('product_image',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    op.create_table('product_tag',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products_product.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags_tag.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tag')
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_users_user_phone_number'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_nickname'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_id'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_email'), table_name='users_user')
    op.drop_table('users_user')
    op.drop_index(op.f('ix_tags_tag_name'), table_name='tags_tag')
    op.drop_index(op.f('ix_tags_tag_id'), table_name='tags_tag')
    op.drop_table('tags_tag')
    op.drop_index(op.f('ix_products_product_id'), table_name='products_product')
    op.drop_table('products_product')
    # ### end Alembic commands ###
