"""empty message

Revision ID: 8fbe30d9f624
Revises: d6ac95d07ff6
Create Date: 2026-06-23 16:03:35.967737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbe30d9f624'
down_revision = 'd6ac95d07ff6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_images', sa.Column('about_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'about_images', 'about_us', ['about_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'about_images', type_='foreignkey')
    op.drop_column('about_images', 'about_id')
    # ### end Alembic commands ###
