"""empty message

Revision ID: b96ad8d35dfc
Revises: 
Create Date: 2023-07-07 16:32:20.852058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96ad8d35dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users_user', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_nickname'), 'users_user', ['nickname'], unique=False)
    op.create_index(op.f('ix_users_user_phone_number'), 'users_user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_phone_number'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_nickname'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_id'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_email'), table_name='users_user')
    op.drop_table('users_user')
    # ### end Alembic commands ###
