"""empty message

Revision ID: e5e9d7bd9a39
Revises: d01d20c1ced9
Create Date: 2024-01-21 05:01:12.134091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e9d7bd9a39'
down_revision = 'd01d20c1ced9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_order',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ankle', sa.Float(), nullable=True),
    sa.Column('foot_length', sa.Float(), nullable=False),
    sa.Column('foot_width', sa.Float(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders_order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders_order')
    op.drop_table('orders_order')
    # ### end Alembic commands ###
